/**
 * §8.5 — the Expense Insights summary.
 *
 * The client asked for an "AI-generated" summary. What they described wanting
 * to *know* — where the money went, whether it is up on last month, what looks
 * wrong — is all derivable from the claims themselves, so this computes it
 * directly. Nothing here is generated by a model, and the UI shouldn't imply
 * otherwise; the value is in surfacing the facts, not in producing prose.
 */
import {
  EXPENSE_CATEGORY_LABELS,
  type ExpenseClaim,
} from "@/src/data/employee-expenses-demo";
import { findDuplicates } from "./duplicate-check";

export type InsightTone = "neutral" | "positive" | "warning";

export interface Insight {
  id: string;
  tone: InsightTone;
  title: string;
  detail: string;
}

/** Amount formatter supplied by the caller (locale-aware). */
type Money = (n: number) => string;

function monthKey(date: string): string {
  return (date ?? "").slice(0, 7);
}

/** The most recent month that actually has claims in it. */
function latestMonth(claims: ExpenseClaim[]): string | null {
  const months = claims.map((c) => monthKey(c.dateSubmitted)).filter(Boolean);
  return months.length ? months.sort().at(-1)! : null;
}

function previousMonthKey(ym: string): string {
  const year = Number(ym.slice(0, 4));
  const month = Number(ym.slice(5, 7));
  const d = new Date(Date.UTC(year, month - 2, 1));
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`;
}

function monthName(ym: string): string {
  const d = new Date(`${ym}-01T00:00:00Z`);
  return Number.isNaN(d.getTime())
    ? ym
    : d.toLocaleDateString("en-GB", { month: "long", year: "numeric" });
}

function sum(claims: ExpenseClaim[]): number {
  return claims.reduce((total, c) => total + c.amount, 0);
}

function median(values: number[]): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0
    ? (sorted[mid - 1] + sorted[mid]) / 2
    : sorted[mid];
}

function daysSince(date: string, now: Date): number {
  const then = new Date(date).getTime();
  if (Number.isNaN(then)) return 0;
  return Math.floor((now.getTime() - then) / 86_400_000);
}

/**
 * Ranked insights — most actionable first, so a truncated list still leads
 * with the thing worth doing something about.
 */
export function buildInsights(
  claims: ExpenseClaim[],
  money: Money,
  now: Date = new Date(),
): Insight[] {
  if (claims.length === 0) return [];

  const insights: Insight[] = [];

  // ── Things needing action ────────────────────────────────────────────────
  // Same rule as the §8.7 "Needs Your Action" card, so the two never disagree.
  const missingReceipts = claims.filter(
    (c) => c.status !== "draft" && (c.attachments?.length ?? 0) === 0,
  );
  if (missingReceipts.length > 0) {
    insights.push({
      id: "missing-receipts",
      tone: "warning",
      title: `${missingReceipts.length} claim${missingReceipts.length === 1 ? "" : "s"} without a receipt`,
      detail: `Worth ${money(sum(missingReceipts))} in total. Claims without a receipt are usually returned before approval.`,
    });
  }

  const rejected = claims.filter((c) => c.status === "rejected");
  if (rejected.length > 0) {
    insights.push({
      id: "rejected",
      tone: "warning",
      title: `${rejected.length} rejected claim${rejected.length === 1 ? "" : "s"}`,
      detail: `${money(sum(rejected))} was turned down. Amend and resubmit, or write them off.`,
    });
  }

  // ── Duplicates (reuses §8.6 detection rather than a second rule) ─────────
  const seen = new Set<string>();
  const duplicatePairs: ExpenseClaim[] = [];
  for (const claim of claims) {
    if (seen.has(claim.id)) continue;
    const matches = findDuplicates(claim, claims, { excludeId: claim.id });
    if (matches.length > 0) {
      duplicatePairs.push(claim);
      seen.add(claim.id);
      for (const m of matches) seen.add(m.claim.id);
    }
  }
  if (duplicatePairs.length > 0) {
    insights.push({
      id: "duplicates",
      tone: "warning",
      title: `${duplicatePairs.length} possible duplicate${duplicatePairs.length === 1 ? "" : "s"}`,
      detail:
        "One or more claims share an amount and merchant with another. Worth checking before they are both reimbursed.",
    });
  }

  // ── Slow reimbursements ─────────────────────────────────────────────────
  const stale = claims.filter(
    (c) => c.status === "approved" && daysSince(c.dateSubmitted, now) > 30,
  );
  if (stale.length > 0) {
    insights.push({
      id: "stale",
      tone: "warning",
      title: `${money(sum(stale))} approved but not yet paid`,
      detail: `${stale.length} claim${stale.length === 1 ? " has" : "s have"} been approved for over 30 days without being reimbursed.`,
    });
  }

  // ── Outliers ────────────────────────────────────────────────────────────
  const byCategory = new Map<string, ExpenseClaim[]>();
  for (const c of claims) {
    byCategory.set(c.category, [...(byCategory.get(c.category) ?? []), c]);
  }
  for (const [category, rows] of byCategory) {
    // A median needs a few data points to mean anything.
    if (rows.length < 4) continue;
    const mid = median(rows.map((r) => r.amount));
    if (mid <= 0) continue;
    const outliers = rows.filter((r) => r.amount > mid * 2);
    if (outliers.length === 0) continue;
    const biggest = outliers.reduce((a, b) => (a.amount > b.amount ? a : b));
    insights.push({
      id: `outlier-${category}`,
      tone: "neutral",
      title: `Unusually large ${EXPENSE_CATEGORY_LABELS[biggest.category].toLowerCase()} claim`,
      detail: `${biggest.title} at ${biggest.merchant} came to ${money(biggest.amount)} — more than double the ${money(mid)} typical for this category.`,
    });
  }

  // ── Where the money went, and which way it is moving ────────────────────
  const thisMonth = latestMonth(claims);
  if (thisMonth) {
    const current = claims.filter(
      (c) => monthKey(c.dateSubmitted) === thisMonth,
    );
    const prevKey = previousMonthKey(thisMonth);
    const previous = claims.filter((c) => monthKey(c.dateSubmitted) === prevKey);

    if (current.length > 0) {
      const currentTotal = sum(current);
      const categoryTotals = new Map<string, number>();
      for (const c of current) {
        categoryTotals.set(
          c.category,
          (categoryTotals.get(c.category) ?? 0) + c.amount,
        );
      }
      const [topCategory, topAmount] = [...categoryTotals.entries()].sort(
        (a, b) => b[1] - a[1],
      )[0];
      const share = Math.round((topAmount / (currentTotal || 1)) * 100);
      insights.push({
        id: "top-category",
        tone: "neutral",
        title: `${EXPENSE_CATEGORY_LABELS[topCategory as ExpenseClaim["category"]]} is your biggest cost this month`,
        detail: `${money(topAmount)} of ${money(currentTotal)} claimed in ${monthName(thisMonth)} — ${share}% of the total.`,
      });

      if (previous.length > 0) {
        const previousTotal = sum(previous);
        const delta = currentTotal - previousTotal;
        const pct = Math.round(
          (Math.abs(delta) / (previousTotal || 1)) * 100,
        );
        insights.push({
          id: "month-on-month",
          tone: delta > 0 ? "neutral" : "positive",
          title:
            delta === 0
              ? "Spend is flat on last month"
              : `Spend is ${delta > 0 ? "up" : "down"} ${pct}% on last month`,
          detail: `${money(currentTotal)} in ${monthName(thisMonth)} against ${money(previousTotal)} in ${monthName(prevKey)}.`,
        });
      }
    }
  }

  return insights;
}
