import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { cn } from "@/src/lib/utils";
import { ThemeProvider } from "@/src/components/themes/theme-provider";
import { DemoSwitcher } from "@/src/components/shared/demo-switcher";
import { OnboardingTutorial } from "@/src/components/shared/onboarding-tutorial";
import { ReduxProvider } from "@/src/lib/stores/redux-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans", inter.variable)}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ReduxProvider>
            <Suspense>
              <DemoSwitcher />
            </Suspense>
            <OnboardingTutorial />
            {children}
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
