import {
  Building2,
  BarChart3,
  CalendarDays,
  Award,
  Zap,
  UserCheck,
  FileText,
} from "lucide-react";

export const SETUP_STEPS = [
  { label: "Complete company profile", done: true, link: "/organization/company" },
  { label: "Add departments", done: true, link: "/organization/departments" },
  { label: "Invite team members", done: true, link: "/organization/employees" },
  { label: "Configure employment types", done: false, link: "/organization/employment-types" },
  { label: "Set up leave policies", done: false, link: "/time-payroll/leave" },
  { label: "Upload onboarding checklist", done: false, link: "/organization/employee-checklist" },
];

export const ALERTS = [
  {
    id: "alert-1",
    level: "warning" as const,
    title: "Scheduled Maintenance — April 10, 2026 · 2:00 AM UTC",
    desc: "The Motee platform will be briefly unavailable for a system upgrade. No action is needed from your end.",
    link: "#",
  },
  // {
  //   id: "alert-2",
  //   level: "critical" as const,
  //   title: "Action Required: Update Your Billing Details",
  //   desc: "Your workspace payment method is expiring soon. Update it in Motee billing settings to avoid interruption.",
  //   link: "#",
  // },
];

export const ANNOUNCEMENTS = [
  {
    id: "ann-1",
    title: "Payroll Engine v2 Now Live",
    body: "Motee has upgraded the payroll processing engine across all workspaces. Faster computation and multi-currency support are now available.",
    tag: "Update",
    type: "Update",
    pinned: true,
    date: "Apr 1, 2026",
  },
  {
    id: "ann-2",
    title: "Q1 2026 Compliance Summary Ready",
    body: "Your Q1 2026 compliance report has been generated by Motee and is available for download in your workspace.",
    tag: "Compliance",
    type: "Report",
    pinned: false,
    date: "Mar 28, 2026",
  },
  {
    id: "ann-3",
    title: "AI Recruitment Assistant Now Available",
    body: "Motee's new AI-assisted hiring feature is live. Enable it from your platform settings to streamline your recruitment process.",
    tag: "Feature",
    type: "Feature",
    pinned: false,
    date: "Mar 20, 2026",
  },
];

export const TAG_COLORS: Record<string, string> = {
  Update: "border-indigo-500/30 bg-indigo-500/10 text-indigo-600 dark:text-indigo-400",
  Compliance: "border-violet-500/30 bg-violet-500/10 text-violet-600 dark:text-violet-400",
  Feature: "border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  Report: "border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400",
  Policy: "border-violet-500/30 bg-violet-500/10 text-violet-600 dark:text-violet-400",
  Benefits: "border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
};

export const HELP_RESOURCES = [
  { id: "h-1", label: "Getting Started with Motee HR", desc: "Step-by-step workspace setup guide from Motee", icon: Zap, link: "#" },
  { id: "h-2", label: "Platform Documentation", desc: "Full Motee HR technical reference and API docs", icon: FileText, link: "#" },
  { id: "h-3", label: "Payroll Configuration Guide", desc: "How to configure and run payroll on Motee", icon: BarChart3, link: "#" },
  { id: "h-4", label: "Motee Community Forum", desc: "Connect with other HR teams using Motee", icon: UserCheck, link: "#" },
];

export const NEXT_ACTIONS = [
  { id: "na-1", label: "Review 3 pending leave requests", icon: CalendarDays, link: "/time-payroll/leave", count: 3, priority: "high" },
  { id: "na-3", label: "Complete 4 performance reviews", icon: BarChart3, link: "/talent/performance", count: 4, priority: "medium" },
  { id: "na-4", label: "Update company organogram", icon: Building2, link: "/organization/structure", count: null, priority: "low" },
  { id: "na-5", label: "Send kudos to top performers", icon: Award, link: "/workspace/kudos", count: null, priority: "low" },
];

export const TIPS = [
  "Use Motee's audit trail to monitor all admin actions and maintain a full compliance record.",
  "Enable two-factor authentication for all HR admin accounts in your Motee security settings.",
  "Set automated reminders in Motee to stay ahead of contract and policy renewal deadlines.",
  "Regularly sync your organisational structure in Motee to keep hierarchy and reporting accurate.",
  "Use Motee's bulk import feature to onboard large employee cohorts quickly and accurately.",
  "Review your Motee workspace health score monthly to ensure your configuration is optimised.",
];

export const NEW_TYPE_COLORS: Record<string, string> = {
  feature: "border-indigo-500/30 bg-indigo-500/10 text-indigo-600 dark:text-indigo-400",
  improvement: "border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  fix: "border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400",
};

export const WHATS_NEW = [
  {
    id: "wn-1",
    type: "feature",
    title: "Skills Gap Analysis",
    desc: "Identify workforce skill shortages with the new Workforce Planning module.",
    date: "Apr 1, 2026",
    link: "#",
  },
  {
    id: "wn-2",
    type: "improvement",
    title: "Improved Payroll Engine",
    desc: "Faster computation and better error messages for payroll runs.",
    date: "Mar 20, 2026",
    link: "#",
  },
  {
    id: "wn-3",
    type: "fix",
    title: "Leave Balance Sync Fix",
    desc: "Resolved issue where accrued leave balances were not updating in real time.",
    date: "Mar 15, 2026",
    link: "#",
  },
];
